Added Anonymous to crossOrigin prop
szimek/signature_pad pull request #542
Opened 2021-06-04 02:04 UTC by pxwee5

Discussion: https://github.com/szimek/signature_pad/issues/399
Tested and it works for my setup. What do we need to get this through ? @szimek

2021-06-04 04:39 UTC, UziTech requested changes

2021-06-04 04:39 UTC, UziTech commented on src/signature_pad.ts
> +    image.crossOrigin = 'Anonymous';
Not sure if it matters but the spec shows it as lowercase. [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)
```suggestion
    image.crossOrigin = 'anonymous';
```

2021-06-04 04:59 UTC, UziTech approved these changes

2021-06-04 13:37 UTC, szimek approved these changes

2021-06-04 13:38 UTC, merged

2021-06-07 20:44 UTC, pxwee5 commented
Any plans to do a patch release in the 2.x.x branch ?

2021-06-13 08:34 UTC, szimek commented
@pxwee5 Yeah, thought it's really hard to say when exactly. Do you have a list of bug fixes that were merged into 3.x branch that you'd like to have in 2.x release? This would help a lot!

2021-06-13 09:28 UTC, pxwee5 commented
Hey @szimek. I'm not aware of any other bug that was fixed in v3 that needs to be in v2. If there are any that you think should fix v2 we should definitely list them out. 
But in my opinion, the `crossOrigin` fix alone is critical enough to warrant a patch fix for v2.